name: CI-CD
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
  push_to_Docker_Hub:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Docker login
       env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
       run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
     - name: Build the Docker image
       run: docker build . --file Dockerfile --tag gali98/test:$(date +%s)
     - name: Docker push
       run: docker push ${{secrets.DOCKER_USERNAME}}/gali98/test
